### ISSUE TITLE
Doesn't work on Ubuntu

### ISSUE THREAD

**Issue by jpelletier** [sporniket/electronic-symbol-generator-for-cad#6]
After successful cloning from git:
jpellet@washu:/home/public/electronique/Kicad$ cd electronic-symbol-generator-for-cad/
jpellet@washu:/home/public/electronique/Kicad/electronic-symbol-generator-for-cad$ ./retest
rm: impossible de supprimer 'dist/*': Aucun fichier ou dossier de ce type
/usr/bin/python3: No module named black
/usr/bin/python3: No module named build

jpellet@washu:/home/public/electronique/Kicad/electronic-symbol-generator-for-cad$ uname -a
Linux washu 5.15.0-89-generic #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jpelletier** [comment]
Installed black and build:
    pip install black build
Installed venv:
    sudo apt install python3.8-venv

After that, ./retest worked.

**Comment by sporniket** [comment]
Thanks for your feedback. I completed the readme about installing the modules required.
